# Generated by Django 3.2.7 on 2021-12-08 08:12

from django.db import migrations, models
import django.db.models.deletion
import learning_logs.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(validators=[learning_logs.models.past_or_future_date], verbose_name='Due date (The date must be in the format MM/DD/YYYY)')),
                ('topic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic')),
            ],
        ),
    ]
